### ISSUE TITLE
Consistent order of drools, optaplanner, jbpm and appformer

### ISSUE THREAD

**Issue by ge0ffrey** [karreiro/kiegroup-website#1]
The chat channels are ordered "drools, jbpm, optaplanner, appformer".
The menu items are ordered "drools, jbpm, appformer, optaplanner".
That should be made consistent.

I personally prefer the order in which they depend on each other, from the ground up:
drools, optaplanner, jbpm, appformer.
(optaplanner uses drools engine, jbpm will use optaplanner engine, the webtooling builds upon all 3 engines)

**Comment by porcelli** [comment]
@ge0ffrey whatever, but for the record, appformer itself doesn't depend on drools nor jbpm. in our build order is the first repo

**Comment by karreiro** [comment]
@ge0ffrey @porcelli thanks for the feedback.

Fixed here https://github.com/karreiro/kiegroup-website/pull/2.
